app:
  name: sentiscope-backend

services:
  - name: backend-api
    type: web
    instance_type: nano
    ports:
      - port: 5000
        protocol: http
    env:
      - PORT=5000
    routes:
      - path: /
        port: 5000
    regions:
      - sin
    scaling:
      min: 1
      max: 1
